# 实时操作

In [1]:
import torch as tor

导个库先

In [2]:
x = tor.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[0],x[1],x[2],x[3]

(tensor(0), tensor(1), tensor(2), tensor(3))

索引也是从0开始的

In [6]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

In [8]:
A = tor.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [9]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

看上面，矩阵的转置

## 对称矩阵

In [10]:
B = tor.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B == B.T #通过==号创建一个二元矩阵

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

向量是标量的推广，矩阵是向量的推广，具有多轴的数据结构（加大矩阵层次）

In [12]:
X= tor.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [14]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [15]:
C= tor.arange(24,dtype=float).reshape(2,3,4)
C

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]], dtype=torch.float64)

In [13]:
A.mean(axis = 0) # 在这里，如果A.mean中的A不是一个内部元素为float的矩阵，那么它就会报错

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [19]:
C.mean()

tensor(11.5000, dtype=torch.float64)

注意事项：要使用广播机制注意要使得轴数（维度）保持不变keepdims

In [26]:
Ax = tor.arange(20,dtype=tor.float32).reshape(5,4)
Axx = tor.arange(4,dtype=tor.float32)
Axy = tor.arange(5,dtype=tor.float32)
Ax,Axx,tor.mv(Ax,Axx)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))